version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands: 
      - npm install -g hexo-cli
      - npm install
      - apt-get install -y curl
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - apt-get update
      - apt-get install -y awscli
      - cd website
      - npm install
      - cd ..

  build: 
    commands:
      - cd website
      - hexo generate

  post_build: 
    commands:
      - cd public/ && aws s3 sync --delete . s3://$BUCKET
